import os

os.environ["AWS_ACCESS_KEY_ID"]="XXXXXXXXXXXXXXX"
os.environ["AWS_SECRET_ACCESS_KEY"]="XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
os.environ["AWS_BUCKET_NAME"]="XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
os.environ["AWS_DEFAULT_REGION"] = "ap-south-1"